export const CLASS = [
  { name: 'Play Group', value: 'Play' },
  { name: 'Nursery', value: 'Nursery' },
  { name: 'LKG', value: 'LKG' },
  { name: 'UKG', value: 'UKG' },
  { name: '1st', value: '1st' },
  { name: '2nd', value: '2nd' },
  { name: '3rd', value: '3rd' },
  { name: '5th', value: '5th' },
  { name: '8th', value: '8th' },
  { name: '9th', value: '9th' },
  { name: '10th', value: '10th' },
  { name: '11th', value: '11th' },
  { name: '12th', value: '12th' },
  { name: 'First Year', value: 'First' },
  { name: 'Second Year', value: 'Second' },
  { name: 'Third Year', value: 'Third' },
  { name: 'Forth year', value: 'Forth' },
];