export const CLASS = [
  { name: 'Play Group', value: 'Play' },
  { name: 'Nursery', value: 'Nursery' },
  { name: 'LKG', value: 'LKG' },
  { name: 'UKG', value: 'UKG' },
  { name: '1st', value: '1st' },
  { name: '2nd', value: '2nd' },
  { name: '3rd', value: '3rd' },
  { name: '5th', value: '5th' },
  { name: '8th', value: '8th' },
  { name: '9th', value: '9th' },
  { name: '10th', value: '10th' },
  { name: '11th', value: '11th' },
  { name: '12th', value: '12th' },
  { name: 'First Year', value: 'First' },
  { name: 'Second Year', value: 'Second' },
  { name: 'Third Year', value: 'Third' },
  { name: 'Forth year', value: 'Forth' },
];

export const strings = {
  EN: {
    noClassFound: 'No classes found',
    update: 'Update',
    add: 'Add',
    addDivision: 'Add Division',
    name: 'Name',
    standard: 'Standard',
    division: 'Division',
    classTeacher: 'Class Teacher',
    startTime: 'Start Time',
    endTime: 'End Time',
    cancel: 'Cancel',
    class: 'Class',
    total: 'Total',
    failed: 'Failed',
    present: 'Present',
    presenty: 'Take Presenty',
    editDetails: 'Edit Details',
    viewStudent: 'View Students',
    addNewClass: 'Add new class',

  },
  MR: {
    noClassFound: 'वर्ग मिळाला नाही',
    update: 'बदला',
    add: 'समाविष्ट ',
    addDivision: 'तुकडी समाविष्ट करा ',
    name: 'नाव ',
    standard: 'इयत्ता ',
    division: 'तुकडी',
    classTeacher: 'वर्गशिक्षक',
    startTime: 'प्रारंभ वेळ',
    endTime: 'समाप्त वेळ',
    cancel: 'रद्द करा ',
    class: 'वर्ग',
    total: 'एकूण',
    failed: 'असमर्थ',
    present: 'हजर',
    presenty: 'हजेरी घ्या',
    editDetails: 'वर्ग बदला',
    viewStudent: 'विद्यार्थी पहा',
    addNewClass: 'नवीन वर्ग बनवा',
  },
};
